<?php
declare(strict_types=1);
if (!defined('ABSPATH')) { exit(); }

wp_register_ability('wpultra/list-atomic-widgets', [
    'label'       => __('List Custom Atomic Widgets', 'wp-ultra-mcp'),
    'description' => __('List the custom atomic widgets generated by create-atomic-widget: name, element_type, status (ok | crashed — a crashed widget fataled at load, was quarantined, and is skipped until regenerated or deleted), files present, and the crash error when any. Pass name to also return the widget\'s generated PHP + Twig sources for review.', 'wp-ultra-mcp'),
    'category'    => 'elementor',
    'input_schema'  => [
        'type'       => 'object',
        'properties' => ['name' => ['type' => 'string']],
        'additionalProperties' => false,
    ],
    'output_schema' => [
        'type'       => 'object',
        'properties' => [
            'success' => ['type' => 'boolean'],
            'widgets' => ['type' => 'array'],
            'sources' => ['type' => 'object'],
        ],
        'required' => ['success'],
    ],
    'execute_callback'    => 'wpultra_list_atomic_widgets_cb',
    'permission_callback' => 'wpultra_permission_callback',
    'meta' => [
        'show_in_rest' => true,
        'mcp'          => ['public' => true, 'type' => 'tool'],
        'annotations'  => ['readonly' => true, 'destructive' => false, 'idempotent' => true],
    ],
]);

function wpultra_list_atomic_widgets_cb(array $input) {
    $crashed = wpultra_widgets_crashed();
    $all = wpultra_widgets_all();

    if (!empty($input['name'])) {
        $name = (string) $input['name'];
        if (!isset($all[$name])) { return wpultra_err('not_found', "No custom widget '$name'."); }
        $dir = $all[$name];
        return wpultra_ok(['sources' => [
            'widget_php' => (string) @file_get_contents($dir . '/widget.php'),
            'twig'       => (string) @file_get_contents($dir . "/templates/{$name}.html.twig"),
            'css'        => is_readable($dir . "/assets/{$name}.css") ? (string) @file_get_contents($dir . "/assets/{$name}.css") : '',
            'status'     => isset($crashed[$name]) ? 'crashed' : 'ok',
            'error'      => (string) ($crashed[$name] ?? ''),
        ]]);
    }

    $rows = [];
    foreach ($all as $name => $dir) {
        $rows[] = [
            'name'         => $name,
            'element_type' => "wpu-$name",
            'status'       => isset($crashed[$name]) ? 'crashed' : 'ok',
            'error'        => (string) ($crashed[$name] ?? ''),
            'has_css'      => is_readable($dir . "/assets/{$name}.css"),
        ];
    }
    return wpultra_ok(['widgets' => $rows]);
}
